#version=0.3
variables:
  GIT_STRATEGY: none
# Cache build results between building and testing
cache:
  key: "$CI_BUILD_REF"
  paths:
  - catkin_ws/
stages:
  - build
  - test
  - deps

# Prepare workspace and checkout the code. This will be executed before every stage
before_script:
  # Environment variablen setzen
  - export SHELL="/bin/bash"
  # Prepare workspace (in folder catkin_ws)
  - sudo apt-get update
  - mrt ci prepare $CI_PROJECT_NAME -c $CI_BUILD_REF
  - cd catkin_ws

build:
  stage: build
  script:
    # Build project and resolve deps at the same time
    - mrt catkin build -rd --default_yes --no-status --no-color $CI_PROJECT_NAME
 
test:
  stage: test
  script:
    # Build code again, in case caching didn't work
    - mrt catkin build -rd --default_yes --no-status --no-color $CI_PROJECT_NAME
    # Run tests
    - source devel/setup.bash
    - mrt catkin run_tests --no-status --no-color $CI_PROJECT_NAME --no-deps
    # Summarize results
    - catkin_test_results --verbose build/$CI_PROJECT_NAME

deps:
    stage: deps
    only:
    # only execute if this is the master branch
    - master
    script:
    # test all dependencies of this package. Exclude packages with -e, include with -i.
    - mrt ci test_deps -f --no-color -f --no-status $CI_PROJECT_NAME

